// FETCH LOGIN TYPES
export const FETCH_LOGIN_START = 'FETCH_LOGIN_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILED = 'FETCH_LOGIN_FAILED';
export const FETCH_LOGIN_STOP = 'FETCH_LOGIN_STOP';

// FETCH LOGOUT TYPES
export const FETCH_LOGOUT_START = 'FETCH_LOGOUT_START';
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS';
export const FETCH_LOGOUT_FAILED = 'FETCH_LOGOUT_FAILED';
export const FETCH_LOGOUT_STOP = 'FETCH_LOGOUT_STOP';

// GET DASHBOARD RESOURCES TYPES
export const GET_DASHBOARD_RESOURCES_START = 'GET_DASHBOARD_RESOURCES_START';
export const GET_DASHBOARD_RESOURCES_SUCCESS = 'GET_DASHBOARD_RESOURCES_SUCCESS';
export const GET_DASHBOARD_RESOURCES_FAILED = 'GET_DASHBOARD_RESOURCES_FAILED';
export const GET_DASHBOARD_RESOURCES_STOP = 'GET_DASHBOARD_RESOURCES_STOP';

// POST DASHBOARD RESOURCES TYPES
export const POST_DASHBOARD_RESOURCES_START = 'POST_DASHBOARD_RESOURCES_START';
export const POST_DASHBOARD_RESOURCES_SUCCESS = 'POST_DASHBOARD_RESOURCES_SUCCESS';
export const POST_DASHBOARD_RESOURCES_FAILED = 'POST_DASHBOARD_RESOURCES_FAILED';
export const POST_DASHBOARD_RESOURCES_STOP = 'POST_DASHBOARD_RESOURCES_STOP';
